---
- name: Python 3.6
  yum:
    name: "python36"
    state: present

- name: Python 3.6-devel
  yum:
    name: "python36-devel"
    state: present

- name: Python 3.6 PIP
  yum:
    name: "python36-pip"
    state: present

- name: PIP upgrade
  pip:
    name: pip
    executable: pip3
    state: latest

- name: pandas 
  pip:
    name: pandas
    executable: /usr/local/bin/pip3

- name: "dask[complete]"
  pip:
    name: "dask[complete]"
    executable: /usr/local/bin/pip3

- name: dask-jobqueue
  pip:
    name: dask-jobqueue
    executable: /usr/local/bin/pip3
